apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  hostNetwork: true
  containers:
    - name: influxdb
      image: influxdb
      ports:
        - containerPort: 8086

