apiVersion: v1
kind: Pod
metadata:
  name: raw-alpine
  annotations:
    security.alpha.kubernetes.io/sysctls: net.ipv4.conf.all.src_valid_mark=1
spec:
  containers:
    - name: alpine-pod
      image: jiexa/wg-client
      command: [ "sh", "-c", "sleep 1h" ]
      imagePullPolicy: Always
      securityContext:
        privileged: true
        capabilities:
          add:
          - NET_ADMIN
            # ports:
            #- containerPort: 51820
            # protocol: UDP

