apiVersion: v1
kind: Service
metadata:
  name: wg-service
  #  labels:
  #  app: wg-client
spec:
  type: NodePort
  selector:
    app: wg-client
  ports:
  - name: vpn
    protocol: UDP
    port: 51820
    targetPort: 51820
    nodePort: 31020
  - name: test
    protocol: UDP
    port: 5555
    targetPort: 5555
    nodePort: 31111
  externalIPs:
  - 134.209.208.29

